const quotes = [
    "Website without visitors is like a ship lost in the horizon. - Dr. Christopher Dayagdag",
    "A website without SEO is like a car with no gas. - Paul Cookson",
    "Being first in the search result organically in Google is the dream of all website owners. - Dr. Chris Dayagdag",
    "A bad website is like a grumpy salesperson. - Jakob Nielsen",
    "Create a website that expresses something about who you are that won't fit into the template available to you on a social networking site. - Jaron Lanier",
    "I figured I should have a website, because that's what everybody was doing. - Dave Portnoy",
    "Great web design without functionality is like a sports car with no engine. - Paul Cookson",
    "To become successful online, you only need to remember the following: Good Heart + Passion + Web Design + SEO + Digital Marketing + Dedication + Positiveness + Patience = Success - Dr. Christopher Dayagdag",
    "Designing a website can be a bit like being a kid and inheriting a sweetshop. It's easy to get carried away. There are so many choices. - Gerry McGovern",
    "Ultimately, users visit your website for its content. Everything else is just the backdrop. - Jakob Nielsen",
    "Search Engine Optimization is no longer about stuffing keywords and attempting to trick Google into ranking your website. It's about creating a user experience that is data driven. We know what customers are searching for and we know how to get them to a page. It's a combination of science and art to successfully rank a website. - Leland Dieno",
    "A website can be like an attic that never fills up. Space is not the problem. Attention is. - Gerry McGovern",
    "Learning HTML and CSS is a lot more challenging than it used to be. Responsive web design adds more layers of complexity to design and develop websites. - Jacob Lett",
    "Don't think of your website as a self-promotion machine, think of it as a self-invention machine. - Austin Kleon",
    "Websites promote you 24/7: No employee will do that. - Paul Cookson",
    "Your website is the window of your business. Keep it fresh, keep it exciting. - Jay Conrad Levinson",
    "Google Analytics is the best friend of all Digital Marketers as it dictates the decision making and success of every website. - Dr. Chris Dayagdag",
    "The only reason to build a website is to change someone. If you can't tell me the change and you can't tell me the someone, then you're wasting your time. - Seth Godin",
    "The power of a website comes from the people using it, not the people making it. - Chris Edwards",
    "Your website is the center of your digital ecosystem, like a brick and mortar location, the experience matters once a customer enters, just as much as the perception they have of you before they walk through the door. - Leland Dieno",
    "The objective of a website is to bring a visitor who brings another visitor. - Amit Kalantri",
    "Today it's not about, 'Get the Traffic,' it's about 'Get the targeted and relevant traffic.' - Adam Audette",
    "Web design is not just about creating pretty layouts. It's about understanding the marketing challenge behind your business. - Mohamed Saad",
    "A website should be designed such that a visitor should go to the cart with confidence and not to your contact page with confusion. - Amit Kalantri",
    "We don't just build websites, we build websites that SELLS. - Dr. Chris Dayagdag",
    "Commit to a niche. Try to stop being everything to everyone. - Andrew Davis",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. - Martin Fowler",
    "Digital design is like painting, except the paint never dries. - Neville Brody",
    "Most sites need to prevent breadth — many many pages that are organized cohesively. A site that presents a single webpage is unlikely to present sufficient depth of content to justify extensive SEO. - Harold Davis",
    "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. - Bill Gates",
    "If there's one thing you learn by working on a lot of different websites, it's that almost any design idea: no matter how appallingly bad, can be made usable in the right circumstances, with enough effort. - Steve Krug",
    "Getting a quality website is not an expense but rather an investment. - Dr. Christopher Dayagdag",
    "There are three responses to a piece of design: yes, no, and WOW! Wow is the one to aim for. - Milton Glaser",
    "People tend to think of the web as a way to get information or perhaps as a place to carry out ecommerce. But really, the web is about accessing applications. Think of each website as an application, and every single click, every single interaction with that site, is an opportunity to be on the very latest version of that application. - Marc Andreessen",
    "The success of every website now depends on search engine optimization and digital marketing strategy. If you are on the first page of all major search engines then you are ahead among your competitors in terms of online sales. - Dr. Christopher Dayagdag",
    "Don't forget: when you start a website, it's not yet a trusted site. So you have to bring people from a trusted site to your site to build up the trust in your site. - James Altucher",
    "A successful website does three things: It attracts the right kinds of visitors. Guides them to the main services or product you offer. Collect Contact details for future ongoing relation. - Mohamed Saad",
    "Responsive Web Design always plays an important role whenever going to promote your website. - Josh Wilson",
    "No one comes to your website to be entertained. They have questions they think you can answer. Content answers questions. - Jay Baer",
    "SEO is an investment just like a tree that needs effort, patience and time to grow before you can see the result. - Dr. Chris Dayagdag",
  ];

  export default quotes